<template>
  <section>
    <div class="admin-section-head"><div><p class="eyebrow">Identity & status</p><h2>主页与关于</h2></div><span v-if="notice" :class="success ? 'success-text' : 'error-text'">{{ notice }}</span></div>
    <form class="profile-form" @submit.prevent="saveAbout">
      <div class="avatar-editor"><div class="avatar-preview"><img v-if="form.avatar" :src="form.avatar" alt="头像预览" /><span v-else>M</span></div><div class="avatar-controls"><div class="field"><label>头像地址</label><input v-model="form.avatar" /></div><ImageUploader compact label="上传头像" @uploaded="form.avatar = $event.url" /></div></div>
      <div class="form-grid two"><div class="field"><label>昵称</label><input v-model="form.nickname" /></div><div class="field"><label>个性签名</label><input v-model="form.signature" /></div></div>
      <div class="field"><label>个人标签（逗号分隔）</label><input v-model="profileTagsText" placeholder="开发者, 记录者, 终身学习" /></div>
      <div class="field"><label>首页副标题</label><textarea v-model="form.hero_subtitle" rows="2"></textarea></div>
      <div class="field"><label>首页心里话（空行分段）</label><textarea v-model="form.home_thought" rows="7"></textarea></div>
      <div class="field"><label>个人说明</label><textarea v-model="form.bio" rows="5"></textarea></div>
      <div class="form-grid two"><div class="field"><label>兴趣爱好</label><textarea v-model="form.interests" rows="4"></textarea></div><div class="field"><label>能力</label><textarea v-model="form.skills" rows="4"></textarea></div></div>
      <div class="field"><label>联系方式</label><textarea v-model="form.contacts" rows="3"></textarea></div>
      <div class="form-grid three"><div class="field"><label>当前心情</label><input v-model="form.mood" /></div><div class="field"><label>短期目标</label><input v-model="form.short_goal" /></div><div class="field"><label>长期目标</label><input v-model="form.long_goal" /></div></div>
      <div class="form-grid two"><div class="field"><label>正在听的歌</label><input v-model="form.current_song" /></div><div class="field"><label>歌曲链接</label><input v-model="form.current_song_url" /></div></div>
      <button class="primary-button" :disabled="saving">{{ saving ? "正在保存…" : "保存主页与关于" }}</button>
    </form>

    <div class="resource-columns">
      <section class="resource-box"><h3>社交账号</h3><form class="quick-form" @submit.prevent="addSocial"><input v-model="socialDraft.name" required placeholder="平台名称" /><input v-model="socialDraft.url" required type="url" placeholder="主页链接" /><button class="primary-button">添加</button></form><div class="resource-list"><article v-for="item in socialLinks" :key="item.id"><input v-model="item.name" /><input v-model="item.url" /><label><input v-model="item.enabled" type="checkbox" /> 显示</label><button @click="saveResource('social-links', item)">保存</button><button class="remove" @click="removeResource('social-links', item)">删除</button></article></div></section>
      <section class="resource-box"><h3>技术栈</h3><form class="quick-form" @submit.prevent="addTech"><input v-model="techDraft.name" required placeholder="技术名称" /><select v-model="techDraft.level"><option v-for="level in 5" :key="level" :value="level">熟悉度 {{ level }}</option></select><button class="primary-button">添加</button></form><div class="resource-list"><article v-for="item in techStacks" :key="item.id"><input v-model="item.name" /><select v-model="item.level"><option v-for="level in 5" :key="level" :value="level">{{ level }} / 5</option></select><label><input v-model="item.enabled" type="checkbox" /> 显示</label><button @click="saveResource('tech-stacks', item)">保存</button><button class="remove" @click="removeResource('tech-stacks', item)">删除</button></article></div></section>
    </div>
  </section>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from "vue";
import ImageUploader from "../ImageUploader.vue";
import { getAdminAbout, updateAdminAbout } from "../../api/about";
import { createAdminResource, deleteAdminResource, getAdminResource, updateAdminResource } from "../../api/content";
const defaults = { avatar: "", nickname: "", signature: "", bio: "", interests: "", skills: "", contacts: "", mood: "", short_goal: "", long_goal: "", current_song: "", current_song_url: "", profile_tags: "", hero_subtitle: "", home_thought: "" };
const form = reactive({ ...defaults }); const saving = ref(false); const notice = ref(""); const success = ref(false); const socialLinks = ref([]); const techStacks = ref([]); const socialDraft = reactive({ name: "", url: "", icon: "", enabled: true, sort_order: 0 }); const techDraft = reactive({ name: "", url: "", icon: "", level: 3, enabled: true, sort_order: 0 });
const profileTagsText = computed({ get() { try { const tags = JSON.parse(form.profile_tags || "[]"); return Array.isArray(tags) ? tags.join(", ") : ""; } catch { return form.profile_tags || ""; } }, set(value) { form.profile_tags = JSON.stringify(value.split(/[,，]/).map((tag) => tag.trim()).filter(Boolean)); } });
async function saveAbout() { saving.value = true; notice.value = ""; try { const { data } = await updateAdminAbout(Object.fromEntries(Object.entries(form).map(([key, value]) => [key, value || null]))); Object.assign(form, defaults, data); success.value = true; notice.value = "主页与关于已保存。"; } catch { success.value = false; notice.value = "保存失败。"; } finally { saving.value = false; } }
async function addSocial() { const { data } = await createAdminResource("social-links", socialDraft); socialLinks.value.push(data); Object.assign(socialDraft, { name: "", url: "", icon: "", enabled: true, sort_order: socialLinks.value.length }); }
async function addTech() { const { data } = await createAdminResource("tech-stacks", techDraft); techStacks.value.push(data); Object.assign(techDraft, { name: "", url: "", icon: "", level: 3, enabled: true, sort_order: techStacks.value.length }); }
async function saveResource(resource, item) { try { await updateAdminResource(resource, item.id, item); success.value = true; notice.value = "条目已保存。"; } catch { success.value = false; notice.value = "条目保存失败。"; } }
async function removeResource(resource, item) { if (!window.confirm(`删除「${item.name}」？`)) return; await deleteAdminResource(resource, item.id); if (resource === "social-links") socialLinks.value = socialLinks.value.filter((entry) => entry.id !== item.id); else techStacks.value = techStacks.value.filter((entry) => entry.id !== item.id); }
onMounted(async () => { const [about, social, tech] = await Promise.allSettled([getAdminAbout(), getAdminResource("social-links"), getAdminResource("tech-stacks")]); if (about.status === "fulfilled") Object.assign(form, defaults, about.value.data || {}); if (social.status === "fulfilled") socialLinks.value = social.value.data; if (tech.status === "fulfilled") techStacks.value = tech.value.data; });
</script>

<style scoped>
.admin-section-head { display: flex; align-items: end; justify-content: space-between; gap: 20px; margin-bottom: 22px; }.admin-section-head h2 { margin: 0; font: 500 32px Georgia, "Songti SC", serif; }.profile-form { padding: 24px; display: grid; gap: 17px; border: 1px solid var(--line); border-radius: 18px; background: rgba(255,255,255,.7); }.form-grid { display: grid; gap: 14px; }.form-grid.two { grid-template-columns: 1fr 1fr; }.form-grid.three { grid-template-columns: repeat(3, 1fr); }.avatar-editor { display: grid; grid-template-columns: 110px 1fr; gap: 18px; align-items: center; }.avatar-preview { width: 110px; height: 110px; display: grid; place-items: center; border-radius: 50%; color: var(--rose-700); background: var(--rose-50); font: 42px Georgia, serif; overflow: hidden; }.avatar-preview img { width: 100%; height: 100%; object-fit: cover; }.avatar-controls { display: grid; grid-template-columns: 1fr 220px; align-items: end; gap: 10px; }.resource-columns { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 26px; }.resource-box { padding: 20px; border: 1px solid var(--line); border-radius: 18px; background: #fff; }.resource-box h3 { margin-top: 0; font: 500 23px Georgia, "Songti SC", serif; }.quick-form { display: grid; grid-template-columns: 1fr 1fr auto; gap: 7px; }.quick-form input, .quick-form select, .resource-list input, .resource-list select { min-width: 0; padding: 9px; border: 1px solid var(--line); border-radius: 9px; }.resource-list { display: grid; gap: 8px; margin-top: 14px; }.resource-list article { padding-top: 8px; display: grid; grid-template-columns: 1fr 1.4fr auto auto auto; gap: 6px; align-items: center; border-top: 1px solid var(--line); }.resource-list label { color: var(--muted); font-size: 11px; white-space: nowrap; }.resource-list button { padding: 7px; border: 0; color: var(--rose-700); background: transparent; }.resource-list .remove { color: #a84d4d; }
@media (max-width: 900px) { .resource-columns { grid-template-columns: 1fr; } .form-grid.three { grid-template-columns: repeat(2, 1fr); } }
@media (max-width: 650px) { .form-grid.two, .form-grid.three, .avatar-controls { grid-template-columns: 1fr; }.avatar-editor { grid-template-columns: 1fr; }.quick-form { grid-template-columns: 1fr; }.resource-list article { grid-template-columns: 1fr 1fr; } }
</style>
